---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: gitlab-runner
spec:
  interval: 10m
  releaseName: gitlab-runner
  chart:
    spec:
      chart: gitlab-runner
      sourceRef:
        kind: HelmRepository
        name: gitlab-runner
  valuesFrom:
    - kind: ConfigMap
      name: gitlab-runner-values
    - kind: Secret
      name: gitlab-runner-api-token
