---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitlab-runner

nameReference:
- kind: ConfigMap
  version: v1
  fieldSpecs:
  - path: spec/valuesFrom/name
    kind: HelmRelease

configMapGenerator:
  - name: gitlab-runner-values
    files:
      - values.yaml=values.yaml

resources:
- helm_repository.yaml
- helm_release.yaml
